version: '3.8' # 파일 형식 버전

services:
  my-web-server: # 서비스 이름
    build: .     # 현재 폴더의 Dockerfile을 사용하여 이미지 빌드
    container_name: nginx-compose # 컨테이너 이름 설정
    ports:
      - "8085:80" # 호스트 8085 포트와 컨테이너 80 포트 연결
    volumes:
      - .:/usr/share/nginx/html # 현재 폴더를 바인드 마운트
    restart: always # 컨테이너가 멈추면 자동으로 다시 시작